services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:inception
    volumes:
      - data_db:/var/lib/mysql
    env_file: 
      - .env
    networks:
      - inception
    ports:
      - "3306:3306"
    restart: on-failure
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:inception
    env_file: .env
    volumes:
      - data:/var/www/html
    depends_on:
      - wordpress
    restart: on-failure
    ports:
      - "443:443"
    networks:
      - inception
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:inception
    env_file: .env
    restart: on-failure
    depends_on:
      - mariadb
    ports:
      - '9000:9000'
    volumes:
      - data:/var/www/html/
    networks:
      - inception

volumes:
  data:
    driver: local
    driver_opts:
      device : ${REPO_PATH}/data
      type : none
      o: bind
  data_db:
    driver: local
    driver_opts:
      device: ${REPO_PATH}/data_db
      type: none
      o: bind


networks:
  inception:
    driver: bridge
