services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:inception
    volumes:
      - data_db:/var/lib/mysql
    env_file: 
      - .env
    networks:
      - inception
    ports:
      - "3306:3306"
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:inception
    env_file: .env
    volumes:
      - data:/var/www/html
    depends_on:
      - wordpress
      - site
    restart: on-failure
    ports:
      - "443:443"
    networks:
      - inception
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:inception
    env_file: .env
    restart: always
    depends_on:
      - mariadb
    ports:
      - '9000:9000'
    volumes:
      - data:/var/www/html/
    networks:
      - inception
    site:
      container_name: site
      build: ./bonus/site
      image: site:inception
      env_file: .env
      restart: on-failure
      ports:
        - '3000:3000'
      volumes:
        - data:/var/www
      networks:
        - inception

volumes:
  data:
    driver: local
    driver_opts:
      device : ${REPO_PATH}/srcs/data
      type : none
      o: bind
  data_db:
    driver: local
    driver_opts:
      device: ${REPO_PATH}/srcs/data_db
      type: none
      o: bind


networks:
  inception:
    driver: bridge
