services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    volumes:
      - ./mariadb/data:/var/lib/mysql
    environment:
      WORDPRESS_DB_NAME: wordpress
      MARIADB_USER_NAME: mzridi
      MARIADB_USER_PASSWORD: mzridi_password
    networks:
      - inception
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - data:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception

networks:
  inception:
    driver: bridge
