services:
  mariadb:
    build: ./mariadb
    volumes:
      - ./mariadb/data:/var/lib/mysql
    environment:
      WORDPRESS_DB_NAME: wordpress
      MARIADB_USER_NAME: mzridi
      MARIADB_USER_PASSWORD: mzridi_password
  nginx:
    build: ./nginx
    ports:
      - "443:443"

networks:
  inception:
    driver: bridge
