# base image
FROM    debian:12.2

# install php and php-curl and php-mysql and php8.2-fpm and curl and sendmail
RUN apt update && apt install -y php8.2 php8.2-curl php8.2-mysql php8.2-fpm curl sendmail 

RUN mkdir -p /run/php/

COPY ./my.sh /my.sh

RUN chmod +x /my.sh

ENTRYPOINT [ "/my.sh" ]

CMD [ "php-fpm8.2", "-F" ]