    FROM debian:12.1

    RUN apt-get update && apt-get upgrade -y

    RUN apt-get install -y vim && apt-get install -y curl

    RUN apt-get install -y php8.2 php8.2-fpm php8.2-mysql

    RUN mkdir -p /var/www/; \
        chown -R www-data:www-data /var/www/; \
        chmod -R 755 /var/www/
    
